---
- name: Setup 1password apt repository
  become: true
  ansible.builtin.deb822_repository:
    name: 1password
    types: deb
    uris: https://downloads.1password.com/linux/debian/amd64
    suites: stable
    components: main
    architectures: amd64
    signed_by: https://downloads.1password.com/linux/keys/1password.asc
  notify:
    - Update apt cache

# Ensure apt sources are clean before updating cache
- import_tasks: remove-apt-list.yaml

- ansible.builtin.meta: flush_handlers

- name: Install 1password desktop app
  become: true
  ansible.builtin.apt:
    name: "1password{% if onepassword_desktop_version not in ['', 'latest'] %}={{ onepassword_desktop_version }}{% endif %}"
    state: "{% if onepassword_desktop_version == 'latest' %}latest{% else %}present{% endif %}"

# Ensure apt sources are clean before attempting install
- import_tasks: remove-apt-list.yaml

- name: Install 1password CLI
  become: true
  when: onepassword_include_cli
  ansible.builtin.apt:
    name: "1password-cli{% if onepassword_cli_version not in ['', 'latest'] %}={{ onepassword_cli_version }}{% endif %}"
    state: "{% if onepassword_cli_version == 'latest' %}latest{% else %}present{% endif %}"

# Ensure apt sources are left clean
- import_tasks: remove-apt-list.yaml
