---
- name: Create 1password directory
  become: true
  ansible.builtin.file:
    state: directory
    path: /opt/1Password
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Download 1password desktop app
  become: true
  # TODO: Add check for files with force update variable
  ansible.builtin.unarchive:
    src: https://downloads.1password.com/linux/tar/stable/{{ ansible_architecture }}/1password-latest.tar.gz
    dest: /opt/1Password
    remote_src: true

- name: Find download directories
  ansible.builtin.find:
    paths: /opt/1Password/
    file_type: directory
    patterns: 1password-*
  register: onepassword_download_dirs

- name: Check at least one directory was found
  ansible.builtin.assert:
    that: onepassword_download_dirs.matched > 0
    fail_msg: No extracted app directories were found.
    success_msg: Found {{ onepassword_download_dirs.matched }} matching directories.

- name: Move files to correct directory
  become: true
  ansible.builtin.copy:
    src: "{{ (onepassword_download_dirs.files | sort(attribute='ctime', reverse=True) | first).path }}/" # Trailing / is required to copy contents
    dest: /opt/1Password
    remote_src: true

- name: Delete download directory
  become: true
  ansible.builtin.file:
    state: absent
    path: "{{ (onepassword_download_dirs.files | sort(attribute='ctime', reverse=True) | first).path }}"

- name: Execute post-install script
  become: true
  ansible.builtin.shell:
    chdir: /opt/1Password
    cmd: ./after-install.sh

- name: Install 1password CLI
  when: onepassword_include_cli # Ensure this line remains!
  ansible.builtin.assert:
    that: true == false
    fail_msg: Not yet implemented.
  # If 1password CLI is not supported via this install method, uncomment and use the assertion below instead.
  # A requested install should fail with an error, rather than fail silently.
  # ansible.builtin.assert:
  #   that: true == false
  #   fail_msg: 1Password CLI installation is not supported via {{ }} install.
